from __future__ import annotations


JOIN_COVERAGE_THRESHOLD = 0.8
NUMERIC_MISSINGNESS_THRESHOLD = 0.2
MISSING_INDICATOR_MIN_RATE = 0.05
HIGH_NULL_DROP_THRESHOLD = 0.95
LOW_CARDINALITY_THRESHOLD = 20
MEDIUM_CARDINALITY_THRESHOLD = 100
OUTLIER_IQR_FACTOR = 3.0
