from __future__ import annotations

DEFAULT_MODEL_NAME = "claude-sonnet-4-6"
DEFAULT_MAX_TOKENS = 8192
DEFAULT_TEMPERATURE = 0.0
DEFAULT_COST_CAP_USD = 1.0
DEFAULT_INPUT_COST_PER_MILLION = 3.0
DEFAULT_OUTPUT_COST_PER_MILLION = 15.0
DEFAULT_CACHE_READ_COST_PER_MILLION = 0.3
DEFAULT_CACHE_WRITE_5M_COST_PER_MILLION = 3.75
DEFAULT_CACHE_WRITE_1H_COST_PER_MILLION = 6.0
DEFAULT_REQUEST_TIMEOUT_SECONDS = 120
DEFAULT_REASONING_ENABLED = True
DEFAULT_THINKING_TYPE = "adaptive"
DEFAULT_THINKING_DISPLAY = "summarized"
DEFAULT_REASONING_EFFORT = "medium"
DEFAULT_CACHE_ENABLED = True
DEFAULT_CACHE_TYPE = "ephemeral"
DEFAULT_CACHE_TTL = "5m"
ANTHROPIC_API_URL = "https://api.anthropic.com/v1/messages"
ANTHROPIC_API_VERSION = "2023-06-01"
